CREATE TABLE aparelho (
       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       nome VARCHAR(100) NOT NULL,
       grupo_muscular VARCHAR(100),
       status VARCHAR(50),
       quantidade INT DEFAULT 1,
       marca VARCHAR(50),
       peso_max INT
);

CREATE TABLE IF NOT EXISTS usuario (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(100),
        email VARCHAR(100) NOT NULL UNIQUE,
        senha VARCHAR(100) NOT NULL
    );